/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/

package main

import (
	"fmt"

	"golang-project-euler/utils"
)

func solveQ2(limit int) int {
	total := 0
	numbers := utils.Fib(limit)

	for _, num := range numbers {
		if num%2 == 0 {
			total += num
		}
	}

	return total
}

func main() {
	fmt.Println(solveQ2(100))
	fmt.Println(solveQ2(4000000))
}
